language: python
python:
    - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt
install:
    - pip install pytest pytest-cov
    - pip install coveralls
# command to run tests, e.g. python setup.py test
sscript:
- py.test --cov . --cov-report term-missing
after_success:
- coveralls