language: python
python:
    - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt
install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install pep8
    - pip install radon
    - pip install mockito
# command to run tests, e.g. python setup.py test
script:
    - py.test --cov . --cov-report term-missing
after_success:
    - coveralls
    - radon raw ./src/.
    - radon raw ./test/.
    - radon cc ./src/.
    - radon cc ./test/.
    - radon mi ./src/.
    - radon mi ./test/.
    - pep8 --statistics -qq ./src
    - pep8 --statistics -qq ./test
notifications:
  email:
    - mbenitezsan@gmail.com